name: PHP Composer

on:
  push:
    branches: [ php-app ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

  deploy:
    runs-on: ubuntu-latest
#    needs: laravel-tests # this job depends on "laravel-tests" having finished
    if: github.ref == 'refs/heads/php-app' # we tell Github to only execute this step if we're on our php-app branch (so we don't put unfinished branches in production)
    steps:
      - name: Deploying to Ubuntu Sever
        uses: appleboy/ssh-action@php-app # An action made to control Linux servers
        with: # We set all our secrets here for the action, these won't be shown in the action logs
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/demo # we move into our app's folder
            git pull origin master --rebase # we pull any changes from git